/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'jared' at '9/29/16 11:58 AM' with Gradle 3.1
 *
 * @author jared, @date 9/29/16 11:58 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
//    def "someLibraryMethod returns true"() {
//        setup:
//        Library lib = new Library()
//        when:
//        def result = lib.someLibraryMethod()
//        then:
//        result == true
//    }
}
